feat: new release process

diff --git a/.github/workflows/draft-release.yaml b/.github/workflows/draft-release.yaml
--- a/.github/workflows/draft-release.yaml
+++ b/.github/workflows/draft-release.yaml
@@ -27,7 +27,7 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'The version you want to release. Ref should be either main for latest releases or a tag for bugfixes. '
+        description: 'The version you want to release. Ref should be either main for latest releases or a tag for bugfixes.'
         required: true
 
 jobs:
@@ -43,29 +43,23 @@ jobs:
           fetch-depth: 0
       - id: check-tag
         name: "Check if tag exists"
-        run: |-
-
+        run: |
           tag=$(git tag -l ${{ inputs.version }})
-
-          if [ ! -z $tag ];
-          then
+          if [ ! -z "$tag" ]; then
             echo "Tag already exists! Please choose another tag."
             exit 1
           fi
       - id: resolve_branch
         name: "Resolve branch prefix (release or bugfix)"
         run: |
-          
-           if [[ ${{ github.ref_name }} == "main" ]];
-           then
-             echo "branch_name=release/${{ inputs.version }}" >> "$GITHUB_OUTPUT"
-           elif [[ ${{ github.ref }} == refs/tags/* ]]
-           then
-             echo "branch_name=bugfix/${{ inputs.version }}" >> "$GITHUB_OUTPUT"
-           else
-             echo "Ref branch does not match required criteria. Should either be "main" or a tag."
-             exit 1
-           fi
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            echo "branch_name=release/${{ inputs.version }}" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
+            echo "branch_name=bugfix/${{ inputs.version }}" >> "$GITHUB_OUTPUT"
+          else
+            echo "Ref branch does not match required criteria. Should either be 'main' or a tag."
+            exit 1
+          fi
 
   draft-new-release:
     name: "Draft a new release"
@@ -78,6 +72,8 @@ jobs:
       pull-requests: write
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
       - name: Create Release or Bugfix branch
         run: git checkout -b ${{ needs.validate-and-prepare.outputs.branch_name }}
       - name: Initialize mandatory git config
@@ -90,18 +86,14 @@ jobs:
         with:
           run: strict
       - name: Replace published DEPENDENCIES file link in NOTICE with the one just created
-        run: sed -i "s#\[DEPENDENCIES\]\(.*\)#\[DEPENDENCIES\]\(DEPENDENCIES\)#g" NOTICE.md
+        run: sed -i "s#\[DEPENDENCIES\]\(.*\)#\[DEPENDENCIES\](DEPENDENCIES)#g" NOTICE.md
       - name: Bump version in gradle.properties
-        run: |-
-          # replace the project's (default) version, could be overwritten later with the -Pversion=... flag
-          sed -i  's/version=.*/version=${{ inputs.version }}/g' gradle.properties
-        env:
-          GITHUB_PACKAGE_USERNAME: ${{ github.actor }}
-          GITHUB_PACKAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          sed -i 's/version=.*/version=${{ inputs.version }}/g' gradle.properties
       - name: Bump version in /charts
         uses: mikefarah/yq@v4.45.2
         with:
-          cmd: |-
+          cmd: |
             find charts -name Chart.yaml -maxdepth 3 | xargs -n1 yq -i '.appVersion = "${{ inputs.version }}" | .version = "${{ inputs.version }}"'
       - name: Update Chart READMEs
         uses: addnab/docker-run-action@v3
@@ -114,12 +106,11 @@ jobs:
         id: make-commit
         run: |
           git add .
-          git commit --message "Prepare release ${{ inputs.version }}"
-
+          git commit -m "Prepare release ${{ inputs.version }}"
           echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
-      - name: Push new branch
+      - name: Push release/bugfix branch
         run: git push origin ${{ needs.validate-and-prepare.outputs.branch_name }}
-      - name: Create pull request
+      - name: Create pull request to main
         if: ${{ github.ref_name == 'main' }}
         uses: thomaseizinger/create-pull-request@1.4.0
         env:
@@ -129,8 +120,16 @@ jobs:
           base: main
           title: Release version ${{ inputs.version }}
           reviewers: ${{ github.actor }}
-          body: |-
+          body: |
             This PR was created in response to a manual trigger of the [draft release workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
             Versions have been bumped in [commit ${{ steps.make-commit.outputs.commit }}](${{ steps.make-commit.outputs.commit }}).
 
-            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
+      - name: Commit version bump to main
+        if: ${{ github.ref_name == 'main' }}
+        run: |
+          git checkout main
+          git pull origin main
+          git merge --no-commit ${{ needs.validate-and-prepare.outputs.branch_name }}
+          git commit -m "Bump version to ${{ inputs.version }} on main"
+          git push origin main
+
